import Head from "next/head";
import Image from "next/image";
import { Inter } from "@next/font/google";
import styles from "@/styles/Home.module.css";
import Link from "next/link";

export async function getStaticProps() {
  const res = await fetch("https://jsonplaceholder.typicode.com/users");
  const data = await res.json();
  return {
    props: { users: data }, // will be passed to the page component as props
  };
}

export default function Home(props) {
  return (
    <>
      <Head>
        <title>NOKHA</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <ul>
          {props.users.map((user) => (
            <li key={user.id}>
              <Link href={"/users/" + user.id}>Name: {user.name}</Link>
            </li>
          ))}
        </ul>
        <h1>HELLO WORLD</h1>
      </main>
    </>
  );
}
